### ISSUE TITLE
Create packet filter

### ISSUE THREAD

**Issue by dyllan124** [KirieZ/Proxy-Snffer#5]
Use the dictionary e.g. TS_IMBCACCOUNT to filter inside the datagridview by using a dropdownbox, dictionary required to add items to filter for.

**Comment by dyllan124** [comment]
can this filter be created soon?

**Comment by KirieZ** [comment]
sure, just need to find a way to keep colors/auto scroll

**Comment by KirieZ** [comment]
implemented on 2d1341b4e84b729962e955e7ccf9816cbb2067b4
